name: "Trigger api-go publish release"

on:
  release:
    types: [published]

jobs:
  trigger-api-go-publish-release:
    uses: rodrigozhou/temporal-api-go/.github/workflows/publish-release.yml@master
    with:
      tag: ${{ github.event.release.tag_name }}
      api_ref: ${{ github.event.release.target_commitish }}
    secrets: inherit
